### ISSUE TITLE
Document jupyter_protocol

### ISSUE THREAD

**Issue by echarles** [takluyver/jupyter_protocol#3]
Jupyter Protocol needs to be documented.

**Comment by kevin-bates** [comment]
Good timing @echarles.  I spent all day yesterday working on splitting the current protocol docs with jupyter_kernel_mgmt.  I hope to get these branches for [protocol](https://github.com/gateway-experiments/jupyter_protocol/commit/3c44ac372fb3d55e7a69c99312fa8ef4e82765c9) and [jupyter_kernel_mgmt](https://github.com/gateway-experiments/jupyter_kernel_mgmt/commit/d55725d26f86eb893e1e88d1bbcdc88068a0c9cc) into PRs this weekend or early next week.  This is proving to be a lot of work to describe the information in jupyter_kernel_mgmt - as evidenced by the empty sections.

@takluyver - I've taken the liberty (knowing it can be undone) to create two repositories on readthedocs.io for [jupyter_protocol](https://readthedocs.org/projects/jupyter-protocol/) and [jupyter_kernel_mgmt](https://readthedocs.org/projects/jupyter-kernel-mgmt/).  I've added you as a maintainer to each.  However, this task could not complete its github integration due to my lack of permissions on the respective github repos.  I'm hoping you can complete that integration or let me know what is necessary on my end.

Since these two docs should cross-reference each other, its important that the readthedocs.io hooks get setup soon and things may take some initial doc pushes to get the referencing working correctly.

Thanks.

**Comment by echarles** [comment]
@kevin-bates can't wait to read the first docs version on readthedocs.io.

@takluyver As mgmt and protocol is getting more traction, how do you see the migration of your repos to jupyter org? Should we open a separated issue for this here? Maybe we should also communicate and ask feedback on https://github.com/jupyter/enhancement-proposals?

**Comment by echarles** [comment]
Closing this, we have now a basic docs on https://jupyter-protocol.readthedocs.io
